apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: credit-risk-prometheus-scaler
  namespace: mlops-serving
  labels:
    app.kubernetes.io/name: kserve-model-serving-platform
    app.kubernetes.io/component: event-driven-autoscaling
spec:
  scaleTargetRef:
    name: credit-risk-router-predictor
  pollingInterval: 10
  cooldownPeriod: 180
  minReplicaCount: 2
  maxReplicaCount: 20
  fallback:
    failureThreshold: 3
    replicas: 5
  advanced:
    horizontalPodAutoscalerConfig:
      name: credit-risk-keda-hpa
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 20
          policies:
            - type: Pods
              value: 4
              periodSeconds: 30
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Percent
              value: 20
              periodSeconds: 60
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.monitoring.svc.cluster.local:9090
        query: sum(rate(kserve_request_total{inferenceservice="credit-risk-router"}[1m]))
        threshold: "120"
        activationThreshold: "15"
